### PR TITLE
BUG: Track matching updates.

### PR DESCRIPTION
**Pull request by nguy**
Still working on this updated implementation of track matching code, but in case there are any comments on the progress thus far. The original kd-tree is a highly modified version of what George Duffy sent me a while back. The Py-ART is a mix of code that @tjlang and I passed back and forth.

@tjlang @swnesbitt

### CODE REVIEW

**Comment by nguy** [comment]
Adding @CowboyGeorge to ping

**Comment by tjlang** [comment]
Do you have a sample script for this feature?

**Comment by swnesbitt** [comment]
I'd like to jump in here - I am tied up today in all day meetings but can take a look tomorrow.

Philosophically, there are some different approaches one could take on this, whether trying to advect polar coordinate bins around with advection, or advecting gridded fields using interpolation, e.g., FFTs or EnKF.  The former code that @CowboyGeorge and I worked on does the former.  I am working on the second right now with some code with @scollis, will try to incorporate within this framework.

**Comment by nguy** [comment]
Here's [a notebook](https://github.com/nguy/Notebooks/blob/master/pytda_along_flight_track.ipynb) that uses the features. Sorry it's a bit disheveled, but I think it gives the general idea of how to use. Unfortunately, I don't have too many known test cases to work with at this point.

@swnesbitt I did not include the advection scheme from @CowboyGeorge code because I was working to generalize. I'm currently trying to apply some subsetting to minimize the KD-tree building time. It's a work in progress and not ready for show time quite yet.

**Comment by scollis** [comment]
I have a whole bunch of code (poorly documented)
here:
http://nbviewer.jupyter.org/github/scollis/advection/blob/master/advection-FFT.ipynb

Uses FFT for advection speeds

I had been working on a PR for Py-ART
https://github.com/ARM-DOE/pyart/pull/344

Dr Scott Collis
Purveyor of lofty observations (Atmospheric Scientist) 
Environmental Science Division
Argonne National Laboratory
Mb: +1 630 235 8025
Of: +1 630 252 0550
Become a Py-ART user today! http://arm-doe.github.io/pyart/ http://arm-doe.github.io/pyart/

**Comment by nguy** [comment]
I updated the notebook to clean things up and put in a separate `RadarMatch` class to use the Py-ART structure. Had to do this while the `join_radars` function in Py-ART may or may not be broken.

I also added a good deal of subsetting that helps optimize the speed and produces better results.

**Comment by nguy** [comment]
The code looks pretty solid to me now.
However, the biggest issue may be the method that the `RadarMatch.near_neighbor` uses. Because it only uses the elevation angle as a first pass for extracting a sweep, the nearest neighbor may not be the best match. Even though the results from this "look the best", the KD-Tree performs much better.

**Comment by nguy** [comment]
Merging since no comments have been made. I think the updates make the code better and further development in terms of an advection scheme can be made in a separate PR. 

The subsetting provided enormous speed savings in building the tree.

**Comment by swnesbitt** [comment]
I will take it from here, sorry for too busy

**Comment by nguy** [comment]
No worries, I hope it is a good starting point for further development.

**Comment by nguy** [comment]
Another note is that the `RadarMatch` class was the more optimized version of the matching code. The `TrackMatch` may need further optimization. I need to test with another dataset (such as WRF fields, or such).

**Pull request merged**
