### PR TITLE
ENH: Make the matching software more robust. Small corrections.

### PR DESCRIPTION
**Pull request by nguy**
Updates to matching software to make more robust. This may be an iterative PR.

The idea was to extend the matching to return points that could be used to retrieve a "curtain" of data.

### CODE REVIEW

**Comment by nguy** [comment]
@swnesbitt This development may be of interest to you. I just got back to it after a time away, so I can't promise it is fully operational. But it does load. :)

**Comment by swnesbitt** [comment]
OK, I have included some improvements in my fork - fixing a few bugs and including a Barnes smoother as an option to the kdtree to retrieve points around the plane.  hope we can sort out the changes easily.

**Comment by swnesbitt** [comment]
Seems like we also may need a gatefilter implementation too - in my use case there was a lot of clutter and skin paint issues that I had to do a heavy-handed automated QC first.  I suppose that may be a job for manual editing if a more careful analysis is necessary...

**Comment by nguy** [comment]
Very nice, I just added the Matchdata arguments and fixed the `pr` to `pr_sweeps`. Hopefully this will make it easier to merge.

**Comment by nguy** [comment]
I think you are correct about a gatefilter-like implementation for awot. Could you make an Issue on this so it does not get forgotten?

Revisiting my thought, I'm not sure gatefilter is a good idea. I'd rather see these radar file types added to Py-ART and edited in Py-ART/ARTview environment.

**Comment by nguy** [comment]
I wonder if you update your code base after this merge this if we could then create a PR on your other changes? I'm happy to help however.

**Pull request merged**
