### PR TITLE
Development branch

### PR DESCRIPTION
**Pull request by adlyons**
Added SkewT files. Testing to see if you can get them to work.

### CODE REVIEW

**Comment by nguy** [comment]
@adlyons - Can you tell me how they fail? Is it read routines, plotting, etc?

**Comment by adlyons** [comment]
when I try and import awot as a whole package I cant reach the additional files Ive added. There is a getdata routine that reads the data in and a graph program that wraps the plotting. It wont import those modules from IO and graph for some reason.

**Comment by nguy** [comment]
@adlyons I just merged the two so that I can work on it.  I already found some odd behavior with PyArt embedded....

**Comment by nguy** [comment]
@adlyons Check out the new commit I just pushed.  
The dropsonde folder needed to be added to the setup.py.  In addition, I had to modify the main AirborneData.py to call the dropsonde section in and read data.  Thus, I also had to create an additional SondeDataFile class to read the data back into the main class.

The import statement for the Dropsondes class in dropsondes.py  was also incorrect and I fixed that.

**Comment by nguy** [comment]
I just tested on a file I found and I get loads of errors.  It looks like the dropsonde file is not being read in properly.  Can you confirm?

**Pull request merged**
